#!/bin/bash
#
INSTANCE="ubuntu"
UNAMEX="ubuntu"
WEBSITENAME="nsfcareer-react-website"
HOST=""
cd /home/$UNAMEX
echo "========================================================="
echo "ENTER SINGLE HOST NAME with http:// suffix. Please don't" 
echo "add "\"/"\" at the end of the URL"
echo "e.g : http://digitalbrainjury.com , http://nsfcareer.io"
echo "========================================================="
echo ""
read -p "Enter DOMAIN NAME: " HOST
echo ""
echo $UNAMEX
#sudo apt-get update && sudo apt-get upgrade -y
sudo apt-get install nginx -y
sudo systemctl enable nginx
# sudo apt-get update -y
sudo apt-get install build-essential libssl-dev -y

# Python dependencies
sudo apt install python-pip -y
sudo pip install Requests
sudo pip install pillow

curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -
sudo apt-get install -y nodejs
sudo apt-get install -y  npm
sudo npm i -g npx
cd /home/$UNAMEX

echo "
server {
    listen 80;
    server_name $HOST;
    location / {
        proxy_pass http://127.0.0.1:3000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-for \$proxy_add_x_forwarded_for;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host \$host;
        proxy_cache_bypass \$http_upgrade;

 }
location /api {
        proxy_pass http://127.0.0.1:3001/api;
        proxy_http_version 1.1;

        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-for \$proxy_add_x_forwarded_for;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host \$host;
        proxy_cache_bypass \$http_upgrade;
     }

}" > /etc/nginx/sites-available/default

#
# at this step you need to update A record on google domains
#
sudo systemctl reload nginx

# Cloning specific brach of React website 
# git clone https://github.com/PSUCompBio/nsfcareer-react-website.git
git clone https://github.com/vradars/nsfcareer-react-website.git
cd /home/$UNAMEX/$WEBSITENAME
sudo npm install
sudo npm install -g concurrently
sudo npm install -g nodemon
# sudo npm run build
sudo npm install -g serve
sudo npm install pm2 -g
sudo npm i -g babel-cli
cd /home/$UNAMEX/$WEBSITENAME/client/
echo -n "export const ENDPOINT = "\"$HOST/api/"\" ;" > ./src/config/constants.js

sudo npm install
export PM2_HOME=/home/$UNAMEX/.pm2
cd ..
echo "====================================================================="
echo "|                **** VERY IMPORTANT STEP *****                      |"
echo "====================================================================="
echo "* Now Update the AWS Credentials and other variables in file given "
echo "  below !"
echo ""
echo "---------------------------------------------------------------------"
echo "* Execute the command given below to open & Edit in Vi Editor"
echo " sudo vi $PWD/config/configuration_keys.json "
echo "======================================================================"
echo ""
